---
Todo:
  primary_key: id
  unique_columns: []
  description:
    id: '{"type":"int(5)","is_nullable":false,"max_length":0,"auto_increment":true}'
    name: '{"type":"varchar(255)","is_nullable":true,"max_length":"255","auto_increment":false}'
    is_done: '{"type":"tinyint(4)","is_nullable":true,"max_length":0,"auto_increment":false}'
  relations: []
  exposed: []
  bindings: []
...
